# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 20:06
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(upload_to='autores/%Y/%m/%d')),
                ('ativo', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='nome')),
            ],
        ),
    ]
