# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='autores/%Y/%m/%d'),
        ),
    ]
