# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_auto_20160901_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
