# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='comprimento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='dada_execucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='lagura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='unidade_de_medida',
            field=models.CharField(choices=[('m', 'Metro'), ('cm', 'Centimetro'), ('mm', 'Milimetro')], default='cm', max_length=2),
        ),
    ]
