# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_auto_20160818_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='altura',
            new_name='badanha',
        ),
    ]
