# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0004_auto_20160818_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='badanha',
            new_name='altura',
        ),
        migrations.AddField(
            model_name='obra',
            name='ops',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
