# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0005_auto_20160818_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='ops',
        ),
    ]
