# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0008_remove_obra_dada_execucao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='ano',
            new_name='data_execucao',
        ),
    ]
