# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 14:08
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0010_auto_20160912_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnica',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='nome'),
        ),
    ]
